export const bidData = [
    {
        first:'',
        second:'',
        third:'',
        fourth:'',
        fifth:'',
        six:''
    },
    {
        first:'',
        second:'',
        third:'',
        fourth:'',
        fifth:'',
        six:''
    },
    {
        first:'',
        second:'',
        third:'',
        fourth:'',
        fifth:'',
        six:''
    },
    {
        first:'',
        second:'',
        third:'',
        fourth:'',
        fifth:'',
        six:''
    },
    {
        first:'',
        second:'',
        third:'',
        fourth:'',
        fifth:'',
        six:''
    },
    {
        first:'',
        second:'',
        third:'',
        fourth:'',
        fifth:'',
        six:''
    },
]